# Generated by Django 2.1.5 on 2019-03-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('testpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Author'),
        ),
        migrations.AddField(
            model_name='question',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpage.Test'),
        ),
        migrations.AddField(
            model_name='image',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpage.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpage.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpage.Type'),
        ),
    ]
